ems/EmployeeManagementSystem/Models/Audit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> AuditTypeId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual AuditAction AuditAction { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Fieldname Fieldname { get; set; }
        public virtual User User { get; set; }
    }
}

ems/EmployeeManagementSystem/Models/AuditAction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditAction
    {
        public AuditAction()
        {
            this.Audits = new HashSet<Audit>();
        }
    
        public int AuditTypeId { get; set; }
        public string AuditAction1 { get; set; }
    
        public virtual ICollection<Audit> Audits { get; set; }
    }
}

ems/EmployeeManagementSystem/Controllers/AuditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EmployeeManagementSystem.Models;

namespace EmployeeManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AuditController : Controller
    {
        //
        // GET: /Audit/
        private EMSEntities12 db = new EMSEntities12();

        public ActionResult Index()
        {
            db = new EMSEntities12();
            List<Audit> al = db.Audits.ToList();
            al = FixList(al);
            return View(al);
        }

        public ActionResult SearchIndex(Nullable<DateTime> DateTime)
        {
            db = new EMSEntities12();
            List<Audit> al = db.Audits.ToList();
            if (DateTime != null)
            {
                List<Audit> returnList = new List<Audit>();
                foreach (Audit a in al)
                {
                    if (a.DateTime > DateTime)
                    {
                        returnList.Add(a);
                    }
                }
                returnList = FixList(returnList);
                return View("Index", returnList);
            }
            al = FixList(al);
            return View("Index", al);
        }

        private List<Audit> FixList(List<Audit> al)
        {
            db = new EMSEntities12();
            for (int x = 0; x < al.Count;x++ )
            {
                if (al[x].Fieldname.Fieldname1 == "ReasonForLeavingId" || al[x].Fieldname.Fieldname1 == "ReasonForLeaving")
                {
                    al[x].Fieldname.Fieldname1 = "ReasonForLeaving";
                    if (al[x].OldValue != "")
                    {
                        Int32 id = Int32.Parse(al[x].OldValue);
                        if (id != 0)
                        {
                            al[x].OldValue = db.ReasonForLeavings.Find(id).ReasonForLeaving1;
                        }
                    }
                    if (al[x].NewValue != "")
                    {
                        Int32 id = Int32.Parse(al[x].NewValue);
                        if (id != 0)
                        {
                            al[x].NewValue = db.ReasonForLeavings.Find(id).ReasonForLeaving1;
                        }
                    }                    
                }
                else if (al[x].Fieldname.Fieldname1 == "SeasonId" || al[x].Fieldname.Fieldname1 == "Season")
                {
                    al[x].Fieldname.Fieldname1 = "Season";
                    if (al[x].OldValue != "")
                    {
                        Int32 id = Int32.Parse(al[x].OldValue);
                        if (id != 0)
                        {
                            al[x].OldValue = db.Seasons.Find(id).Season1;
                        }
                    }
                    if (al[x].NewValue != "")
                    {
                        Int32 id = Int32.Parse(al[x].NewValue);
                        if (id != 0)
                        {
                            al[x].NewValue = db.Seasons.Find(id).Season1;
                        }
                    }   
                }
            }
            return al;
        }

    }
}

ems/EmployeeManagementSystem/Views/Audit/Index.cshtml
@model IEnumerable<EmployeeManagementSystem.Models.Audit>

@{
    ViewBag.Title = "Audit Table";
}

<script type="text/javascript">

    $(function () {
        document.getElementById('DateTime').focus();
    });

</script>

<h2>Audit Table</h2>

<p>
    @using (Html.BeginForm("SearchIndex","Audit",FormMethod.Post ,new{DateTime = "SearchForm"})){
        <p>     
            Audits Since: @Html.TextBox("DateTime", "", new {@class="SearchTextBox" })<br />
            <input type="submit" value="Search"  onclick="$('#SearchForm').submit()" />
        </p>
    }
</p>

<table>
    <tr>
        <th>
            Username
        </th>
        <th>
            Date
        </th>
        <th>
            Audit Type
        </th>
        <th>
            Field
        </th>
        <th>
            Old Value
        </th>
        <th>
            New Value
        </th>
        <th>
            Employee SIN
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AuditAction.AuditAction1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fieldname.Fieldname1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OldValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NewValue)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Employee.SIN_BN) 
        </td>
    </tr>
}

</table>